Style/PercentLiteralDelimiters:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# this would cause errors with long lanes
Metrics/BlockLength:
  Enabled: false

# Catch all errors
Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Better too much 'return' than one missing
Style/RedundantReturn:
  Enabled: false

# Having if in the same line might not always be good
Style/IfUnlessModifier:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 320


# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 370

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 18

# Sometimes it's easier to read without guards
Style/GuardClause:
  Enabled: false

# We allow both " and '
Style/StringLiterals:
  Enabled: false

# e.g.
# def self.is_supported?(platform)
# we may never use `platform`
Lint/UnusedMethodArgument:
  Enabled: false

# This would reject is_ in front of methods
# We use `is_supported?` everywhere already
Style/PredicateName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.0
  Include:
    - '*/lib/assets/*Template'
    - '*/lib/assets/*TemplateAndroid'
  Exclude:
    - '**/lib/assets/custom_action_template.rb'
    - './vendor/**/*'
    - '**/lib/assets/DefaultFastfileTemplate'
    - '**/spec/fixtures/broken_files/broken_file.rb'

# They have not to be snake_case
Style/FileName:
  Exclude:
    - '**/Dangerfile'
    - '**/Brewfile'
    - '**/Gemfile'
    - '**/Podfile'
    - '**/Rakefile'
    - '**/Fastfile'
    - '**/Deliverfile'
    - '**/Snapfile'
    - '**/*.gemspec'

# We're not there yet
Style/Documentation:
  Enabled: false

# Added after upgrade to 0.38.0
Style/MutableConstant:
  Enabled: false

# ( ) for method calls
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - 'require'
    - 'require_relative'
    - 'fastlane_require'
    - 'gem'
    - 'program'
    - 'command'
    - 'raise'
    - 'attr_accessor'
    - 'attr_reader'
    - 'desc'
    - 'lane'
    - 'private_lane'
    - 'platform'
    # rspec tests code below
    - 'to'
    - 'describe'
    - 'it'
    - 'be'
    - 'context'
    - 'before'
    - 'after'
